[build]
  # tu comando habitual, p.ej. "npm run build"
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

  # si este comando sale con 0, NETLIFY SALTA el build
  ignore = "node netlify-ignore.js"
